# Generated by Django 4.2.4 on 2023-08-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_thumbnail_alter_course_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
